/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mars_marsview_utils_NdkTest */

#ifndef _Included_com_mars_marsview_utils_NdkTest
#define _Included_com_mars_marsview_utils_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mars_marsview_utils_NdkTest
 * Method:    getStringFromc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mars_marsview_utils_NdkTest_getStringFromc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
