/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mars_marsview_utils_Bmp2JbigMannger */

#ifndef _Included_com_mars_marsview_utils_Bmp2JbigMannger
#define _Included_com_mars_marsview_utils_Bmp2JbigMannger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mars_marsview_utils_Bmp2JbigMannger
 * Method:    getByteDataFromc
 * Signature: ([BII[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mars_marsview_utils_Bmp2JbigMannger_getByteDataFromc
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
