/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mars_marsview_utils_RSAEncrypt */

#ifndef _Included_com_mars_marsview_utils_RSAEncrypt
#define _Included_com_mars_marsview_utils_RSAEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mars_marsview_utils_RSAEncrypt
 * Method:    RSAPublickeyEncrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mars_marsview_utils_RSAEncrypt_RSAPublickeyEncrypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
